/**
 * Mirror of src/walkthroughs/courses.ts. Kept in sync manually until we
 * factor into a shared package. The worker uses this for prompt assembly
 * and topic classification.
 */
export interface Topic {
  id: string;
  title: string;
  blurb: string;
  strategicAnchor: string;
  exampleProblem: string;
}

export interface Course {
  id: string;
  title: string;
  blurb: string;
  topics: Topic[];
}

export const COURSES: Course[] = [
  {
    id: 'algebra',
    title: 'College Algebra',
    blurb: 'Equations, inequalities, functions, polynomials, factoring.',
    topics: [
      { id: 'real-numbers-exponents', title: 'Real Numbers & Exponents', blurb: 'Order of operations, integer and rational exponents, radical rules.', strategicAnchor: 'Same base: add exponents ($x^a x^b = x^{a+b}$). Power of a power: multiply ($(x^a)^b = x^{ab}$). Negative flips ($x^{-n}=1/x^n$). Fractional is a radical: $x^{m/n}=\\sqrt[n]{x^m}$.', exampleProblem: 'Simplify: $\\left(\\dfrac{4 x^{3} y^{-2}}{8 x^{-1} y^{3}}\\right)^{-2}$' },
      { id: 'linear-equations', title: 'Linear Equations', blurb: 'Solve $ax + b = c$ by isolating the variable.', strategicAnchor: 'Clear fractions by multiplying through by the LCD, distribute, collect like terms, then undo operations in reverse order.', exampleProblem: 'Solve: $\\dfrac{3x - 5}{2} - \\dfrac{x + 1}{3} = 4$' },
      { id: 'inequalities-absolute-value', title: 'Inequalities & Absolute Value', blurb: 'Linear inequalities and $|ax + b|$ equations.', strategicAnchor: '$|E|<c \\Rightarrow -c<E<c$ (sandwich). $|E|>c \\Rightarrow E<-c$ or $E>c$ (split). Flip the sign whenever you multiply or divide by a negative.', exampleProblem: 'Solve $|2x - 5| \\ge 7$ and express the solution in interval notation.' },
      { id: 'linear-systems', title: 'Systems of Linear Equations', blurb: 'Two equations, two unknowns — substitute or eliminate.', strategicAnchor: 'One variable already isolated? Substitute. Coefficients line up to cancel? Eliminate. Pick whichever is less work.', exampleProblem: 'Solve the system: $$\\begin{cases} 2x + 3y = 12 \\\\ x - y = 1 \\end{cases}$$' },
      { id: 'polynomial-factoring', title: 'Polynomial Factoring', blurb: 'GCF, grouping, and special-product patterns.', strategicAnchor: 'GCF first, always. Then count terms: 2 → difference of squares or cubes; 3 → trinomial; 4 → grouping.', exampleProblem: 'Factor completely: $3x^4 - 24x$' },
      { id: 'factoring-quadratics', title: 'Factoring x² + bx + c', blurb: 'Two numbers that add to $b$ and multiply to $c$.', strategicAnchor: 'Find two integers that multiply to $c$ and add to $b$. If $c>0$ they share $b$\'s sign; if $c<0$ they split signs.', exampleProblem: 'Factor: $x^2 + 11x + 30$' },
      { id: 'rational-expressions', title: 'Rational Expressions', blurb: 'Simplify, multiply, divide, and combine fractions of polynomials.', strategicAnchor: 'Factor every numerator and denominator first, then cancel. For $\\pm$: build the LCD from the highest power of each distinct factor.', exampleProblem: 'Simplify: $\\dfrac{x^2 - 4}{x^2 - x - 6} \\div \\dfrac{x + 2}{x - 3}$' },
      { id: 'rational-equations', title: 'Rational Equations', blurb: 'Equations with variables in denominators.', strategicAnchor: 'Multiply through by the LCD to clear denominators, solve, then discard any root that zeroes an original denominator.', exampleProblem: 'Solve: $\\dfrac{2}{x-1} + \\dfrac{1}{x+1} = \\dfrac{4}{x^2 - 1}$' },
      { id: 'completing-the-square', title: 'Completing the Square', blurb: 'Manufacture a perfect-square trinomial by adding the right constant.', strategicAnchor: 'Add and subtract $(b/2)^2$ to turn $x^2+bx$ into $(x+b/2)^2$. Then read off vertex form or solve.', exampleProblem: 'Solve by completing the square: $x^2 + 6x + 5 = 0$' },
      { id: 'quadratic-formula', title: 'The Quadratic Formula', blurb: 'When factoring fails, plug into $x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$.', strategicAnchor: 'Check the discriminant $b^2-4ac$ first: positive → two real, zero → one repeated, negative → two complex. Then plug into the formula.', exampleProblem: 'Solve: $2x^2 - 5x + 1 = 0$' },
      { id: 'quadratic-inequalities', title: 'Quadratic Inequalities', blurb: 'Find where a quadratic is positive or negative on the number line.', strategicAnchor: 'Find the roots, then test signs in each interval between them. Flip only when multiplying or dividing by a negative.', exampleProblem: 'Solve: $x^2 - 3x - 4 > 0$' },
      { id: 'functions-inverses', title: 'Functions & Inverses', blurb: 'Domain, composition $(f \\circ g)(x)$, and inverse $f^{-1}(x)$.', strategicAnchor: 'Domain bans: zero denominators, negatives under even roots, non-positive log arguments. To invert: swap $x$ and $y$, solve for $y$, restrict if needed.', exampleProblem: 'Given $f(x) = \\dfrac{2x + 3}{x - 1}$, find $f^{-1}(x)$ and state its domain.' },
    ],
  },
  {
    id: 'precalc',
    title: 'Precalculus',
    blurb: 'Trig identities, exponentials and logs, conic sections, sequences.',
    topics: [
      { id: 'function-transformations', title: 'Function Transformations', blurb: 'Shifts, stretches, reflections — building graphs from parents.', strategicAnchor: 'Outside $f$ behaves as written (affects $y$). Inside $f$ behaves backwards (affects $x$): $f(x-h)$ shifts right by $h$, $f(bx)$ compresses horizontally by $b$.', exampleProblem: 'Describe the graph of $g(x) = -2 \\cdot f(3(x - 1)) + 4$ as a sequence of transformations of $f(x)$.' },
      { id: 'polynomial-rational-functions', title: 'Polynomial & Rational Functions', blurb: 'End behavior, asymptotes, and sketching graphs.', strategicAnchor: 'Polynomials: leading term sets end behavior; root multiplicity sets shape (odd crosses, even touches). Rationals: non-canceling zero of denominator → vertical asymptote; degree comparison → horizontal.', exampleProblem: 'Sketch $f(x) = \\dfrac{x^2 - 4}{x^2 - x - 2}$: find all intercepts, asymptotes, and the holes (if any).' },
      { id: 'conic-sections', title: 'Conic Sections', blurb: 'Recognize circles, ellipses, parabolas, hyperbolas from the equation.', strategicAnchor: 'Look at the squared-term coefficients. Same → circle; different positive → ellipse; only one squared term → parabola; opposite signs → hyperbola.', exampleProblem: 'Identify the conic and rewrite in standard form: $x^2 + 4y^2 - 6x + 16y + 9 = 0$' },
      { id: 'exponential-equations', title: 'Exponential Equations', blurb: 'Variable in the exponent — bring it down with a log.', strategicAnchor: 'Variable in the exponent? Take $\\ln$ of both sides. $\\ln(a^x)=x\\ln a$ brings it down.', exampleProblem: 'Solve: $5^{x+1} = 12$' },
      { id: 'log-rules', title: 'Logarithm Rules', blurb: 'Convert products, quotients, and powers via the log laws.', strategicAnchor: '$\\log(ab)=\\log a+\\log b$, $\\log(a/b)=\\log a-\\log b$, $\\log(a^n)=n\\log a$. After solving, check every argument stayed positive.', exampleProblem: 'Solve: $\\log_2(x) + \\log_2(x - 2) = 3$' },
      { id: 'unit-circle-trig', title: 'Trig on the Unit Circle', blurb: 'Sine, cosine, and tangent from $(x, y)$ on the unit circle.', strategicAnchor: 'On the unit circle, $\\cos\\theta$ is $x$ and $\\sin\\theta$ is $y$. Quadrant signs by ASTC: All, Sin, Tan, Cos positive in Q1–Q4.', exampleProblem: 'Without a calculator, find $\\sin\\left(\\dfrac{5\\pi}{6}\\right)$, $\\cos\\left(\\dfrac{4\\pi}{3}\\right)$, and $\\tan\\left(\\dfrac{7\\pi}{4}\\right)$.' },
      { id: 'pythagorean-identities', title: 'Pythagorean Identities', blurb: 'sin²x + cos²x = 1, and its two cousins.', strategicAnchor: '$\\sin^2+\\cos^2=1$. Divide by $\\cos^2$ → $\\tan^2+1=\\sec^2$. Divide by $\\sin^2$ → $1+\\cot^2=\\csc^2$. Pick the form that matches what you see.', exampleProblem: 'Simplify: $\\dfrac{\\sin^2 x}{1 - \\cos x}$' },
      { id: 'sum-difference-identities', title: 'Sum, Difference & Double-Angle Identities', blurb: '$\\sin(A \\pm B)$, $\\cos(A \\pm B)$, $\\sin(2A)$, $\\cos(2A)$.', strategicAnchor: '$\\sin(A\\pm B)=\\sin A\\cos B \\pm \\cos A\\sin B$ (sign matches). $\\cos(A\\pm B)=\\cos A\\cos B \\mp \\sin A\\sin B$ (sign flips). Double-angle is the same with $B=A$.', exampleProblem: 'Find the exact value of $\\sin\\left(\\dfrac{7\\pi}{12}\\right)$ using a sum identity.' },
      { id: 'solving-trig-equations', title: 'Solving Trig Equations', blurb: 'Find all $x$ with $\\sin x = a$, etc., over an interval or all reals.', strategicAnchor: 'Find one reference angle, then add the period. Sin and cos give two solution families per cycle; tan gives one.', exampleProblem: 'Solve $2\\sin x - 1 = 0$ on $[0, 2\\pi)$.' },
      { id: 'polar-complex', title: 'Polar Coordinates & Complex Numbers', blurb: 'Convert between $(r, \\theta)$ and $(x, y)$; $a + bi$ in polar form.', strategicAnchor: '$x=r\\cos\\theta$, $y=r\\sin\\theta$, $r^2=x^2+y^2$. In polar, multiplication is clean: multiply moduli, add angles ($re^{i\\theta}$).', exampleProblem: "Find $(1 + i)^{10}$ by converting to polar form and applying De Moivre's theorem." },
      { id: 'arithmetic-geometric-sequences', title: 'Arithmetic & Geometric Sequences', blurb: 'Closed-form formulas and partial sums.', strategicAnchor: 'Constant difference → arithmetic: $a_n=a_1+(n-1)d$. Constant ratio → geometric: $a_n=a_1 r^{n-1}$.', exampleProblem: 'Find the sum of the first 20 terms of $3, 7, 11, 15, \\ldots$' },
      { id: 'series-sigma', title: 'Series & Sigma Notation', blurb: 'Read $\\sum$ notation and compute finite + infinite geometric sums.', strategicAnchor: 'Geometric: $S_n=a_1\\dfrac{1-r^n}{1-r}$; infinite if $|r|<1$ → $\\dfrac{a_1}{1-r}$. Otherwise look for telescoping.', exampleProblem: 'Evaluate: $\\displaystyle\\sum_{n=1}^{\\infty} \\dfrac{3}{4^n}$' },
    ],
  },
  {
    id: 'calc-1',
    title: 'Calculus I',
    blurb: 'Limits, derivatives, optimization, related rates.',
    topics: [
      { id: 'limits', title: 'Computing Limits', blurb: 'Direct sub first, then factor/cancel for indeterminate forms.', strategicAnchor: 'Plug in first. If you get $0/0$ or $\\infty/\\infty$: factor, conjugate, or L\'Hôpital. Check one-sided when behavior splits.', exampleProblem: 'Compute: $\\displaystyle\\lim_{x \\to 2} \\dfrac{x^2 - 4}{x - 2}$' },
      { id: 'continuity-ivt', title: 'Continuity & the IVT', blurb: 'A function is continuous when its limit equals its value.', strategicAnchor: 'Continuous = limit equals value. IVT: continuous on $[a,b]$ and $N$ between $f(a),f(b)$ → some $c$ in between hits $N$. Use it to prove a root exists without finding it.', exampleProblem: 'Show that $f(x) = x^3 + x - 1$ has a root in $(0, 1)$.' },
      { id: 'derivative-definition', title: 'Derivative as a Limit', blurb: "$f'(x) = \\lim_{h \\to 0} \\dfrac{f(x+h) - f(x)}{h}$.", strategicAnchor: '$f\'(x)=\\lim_{h\\to 0}\\dfrac{f(x+h)-f(x)}{h}$. Expand the top, factor an $h$ out, cancel, then send $h\\to 0$.', exampleProblem: "Use the limit definition to find $f'(x)$ for $f(x) = \\dfrac{1}{x + 2}$." },
      { id: 'differentiation-rules', title: 'Differentiation Rules', blurb: 'Power, product, quotient, chain — knowing which to apply first.', strategicAnchor: 'Read the outermost structure: sum → split; product → product rule; quotient → quotient rule; composition → chain rule. Chain rule whenever there\'s an inside function.', exampleProblem: 'Differentiate: $f(x) = \\dfrac{x^2 \\sin(3x)}{e^x}$' },
      { id: 'derivatives-trig-exp-log', title: 'Derivatives of Trig, Exp & Log', blurb: 'Special forms: $\\sin$, $\\cos$, $\\tan$, $e^x$, $\\ln x$.', strategicAnchor: '$\\sin\\to\\cos$, $\\cos\\to-\\sin$, $\\tan\\to\\sec^2$, $e^x\\to e^x$, $\\ln x\\to 1/x$. Always multiply by the derivative of the inside.', exampleProblem: 'Differentiate: $f(x) = e^{x^2} \\tan(\\ln x)$.' },
      { id: 'implicit-differentiation', title: 'Implicit Differentiation', blurb: 'When $y$ is tangled with $x$ — differentiate both sides treating $y$ as $y(x)$.', strategicAnchor: 'Differentiate every term in $x$. Each $y$ picks up a $dy/dx$ tag (chain rule). Then solve algebraically for $dy/dx$.', exampleProblem: 'Find $\\dfrac{dy}{dx}$ for $x^2 + xy + y^2 = 7$.' },
      { id: 'curve-sketching', title: 'Curve Sketching', blurb: "Use $f'$ and $f''$ to find shape, extrema, and inflection points.", strategicAnchor: '$f\'=0$ → critical points; sign of $f\'$ → increase/decrease. $f\'\'=0$ → inflection candidates; sign of $f\'\'$ → concavity. Second-derivative test classifies extrema.', exampleProblem: 'Sketch $f(x) = x^3 - 6x^2 + 9x + 1$: find all extrema and inflection points.' },
      { id: 'related-rates', title: 'Related Rates', blurb: 'Two changing quantities tied by an equation; given one rate, find the other.', strategicAnchor: 'Write the relating equation, differentiate w.r.t. $t$, substitute numbers LAST. Substituting early freezes a variable that should still be moving.', exampleProblem: 'A 10-ft ladder slides down a wall. The bottom moves at 2 ft/s away from the wall. How fast is the top falling when the bottom is 6 ft from the wall?' },
      { id: 'mean-value-theorem', title: 'Mean Value Theorem', blurb: 'Continuous + differentiable → average rate is achieved as an instantaneous rate somewhere.', strategicAnchor: 'Continuous on $[a,b]$ + differentiable on $(a,b)$ → some $c$ has $f\'(c)=\\dfrac{f(b)-f(a)}{b-a}$. Rolle is the special case with $f(a)=f(b)$, forcing $f\'(c)=0$.', exampleProblem: 'Verify the MVT for $f(x) = x^3 - x$ on $[0, 2]$ and find the value(s) of $c$.' },
      { id: 'optimization', title: 'Optimization', blurb: 'Maximize or minimize a quantity subject to a constraint.', strategicAnchor: 'Use the constraint to write the objective in one variable. Set its derivative to zero. Check endpoints too.', exampleProblem: 'Find the dimensions of the rectangle of maximum area inscribed in a semicircle of radius 5.' },
      { id: 'lhopital', title: "L'Hôpital's Rule", blurb: 'Differentiate top and bottom to crack indeterminate limits.', strategicAnchor: 'Confirm $0/0$ or $\\infty/\\infty$ first. Differentiate top and bottom separately (not as a quotient). Repeat as needed; convert other indeterminate forms to one of these.', exampleProblem: 'Compute: $\\displaystyle\\lim_{x \\to 0} \\dfrac{\\sin x - x}{x^3}$' },
      { id: 'antiderivatives-ftc', title: 'Antiderivatives & the FTC', blurb: 'Integration as inverse of differentiation; FTC connects them.', strategicAnchor: 'Reverse the power rule: $\\int x^n dx=\\dfrac{x^{n+1}}{n+1}+C$ (the $n=-1$ case is $\\ln|x|$). FTC: $\\int_a^b f\\,dx=F(b)-F(a)$ when $F\'=f$.', exampleProblem: 'Compute: $\\displaystyle\\int_0^{\\pi/2} (3\\sin x + 2x) \\, dx$' },
    ],
  },
  {
    id: 'calc-2',
    title: 'Calculus II',
    blurb: 'Integration techniques, series, parametrics and polar.',
    topics: [
      { id: 'riemann-sums', title: 'Riemann Sums & Definite Integrals', blurb: 'Build the integral as a limit of rectangle sums.', strategicAnchor: '$\\sum f(x_i^*)\\Delta x \\to \\int_a^b f\\,dx$ as $n\\to\\infty$. Recognize a Riemann-sum limit by spotting the $\\Delta x$ and a sample point $x_i^*$.', exampleProblem: 'Express $\\displaystyle\\lim_{n \\to \\infty} \\sum_{i=1}^{n} \\dfrac{2i^2}{n^3}$ as a definite integral and evaluate it.' },
      { id: 'u-substitution', title: 'u-Substitution', blurb: 'Reverse the chain rule by spotting an inner function and its derivative.', strategicAnchor: 'Spot an inner function and its derivative. Let $u=g(x)$, $du=g\'(x)\\,dx$; the integral becomes $\\int f(u)\\,du$. Change bounds for definite integrals.', exampleProblem: 'Compute: $\\displaystyle\\int x \\cos(x^2) \\, dx$' },
      { id: 'integration-by-parts', title: 'Integration by Parts', blurb: 'Reverse the product rule. Pick $u$ via LIATE.', strategicAnchor: '$\\int u\\,dv=uv-\\int v\\,du$. Pick $u$ by LIATE (Log, Inverse-trig, Algebraic, Trig, Exp — leftmost wins). For polynomial × $e^x$ or $\\sin/\\cos$: use the tabular (DI) trick — differentiate the polynomial down one column to 0, integrate the other down the next, multiply across the diagonals with alternating signs. Kills $\\int x^3 e^x\\,dx$ in one diagram, no recursion.', exampleProblem: 'Compute: $\\displaystyle\\int x^2 \\ln x \\, dx$' },
      { id: 'trig-substitution', title: 'Trigonometric Substitution', blurb: 'When you see $\\sqrt{a^2 \\pm x^2}$ or $\\sqrt{x^2 - a^2}$, trade $x$ for a sin/tan/sec.', strategicAnchor: '$\\sqrt{a^2-x^2}\\Rightarrow x=a\\sin\\theta$; $\\sqrt{a^2+x^2}\\Rightarrow a\\tan\\theta$; $\\sqrt{x^2-a^2}\\Rightarrow a\\sec\\theta$. Each kills the radical via Pythagoras.', exampleProblem: 'Compute: $\\displaystyle\\int \\dfrac{1}{\\sqrt{9 - x^2}} \\, dx$' },
      { id: 'partial-fractions', title: 'Partial Fraction Decomposition', blurb: 'Split a rational function into pieces you can integrate separately.', strategicAnchor: 'Factor the denominator. Linear $(x-r)\\to A/(x-r)$; repeated → also add $B/(x-r)^2$; irreducible quadratic → $(Cx+D)/Q$. Heaviside cover-up for distinct linear factors: to find $A$, *cover* $(x-r)$ in the original and plug $x=r$ into what remains. No system of equations.', exampleProblem: 'Compute: $\\displaystyle\\int \\dfrac{3x + 5}{(x - 1)(x + 2)} \\, dx$' },
      { id: 'improper-integrals', title: 'Improper Integrals', blurb: 'Integrals over infinite intervals or with vertical asymptotes.', strategicAnchor: 'Replace the bad endpoint with a parameter and take the limit. Finite limit → converges; otherwise diverges. Split at any interior singularity.', exampleProblem: 'Does $\\displaystyle\\int_0^1 \\dfrac{1}{\\sqrt{x}} \\, dx$ converge? If so, evaluate it.' },
      { id: 'sequences', title: 'Sequences', blurb: 'Limits of $a_n$, monotonicity, and bounded sequences.', strategicAnchor: 'Treat $n$ as continuous and apply L\'Hôpital, ratio tricks, or squeeze. Monotone + bounded → converges (safest existence argument).', exampleProblem: 'Determine whether $a_n = \\dfrac{n^2 + 3n}{2n^2 - 1}$ converges, and find its limit if so.' },
      { id: 'series-convergence', title: 'Series Convergence Tests', blurb: "Choose the right test based on the summand's shape.", strategicAnchor: 'Always check $a_n\\to 0$ first — if not, it diverges immediately. Then route by shape: alternating sign → AST; $1/n^p$ → $p$-test ($p>1$); factorial or $r^n$ → ratio; resembles a known series → comparison.', exampleProblem: 'Does $\\displaystyle\\sum_{n=2}^{\\infty} \\dfrac{1}{n \\ln n}$ converge?' },
      { id: 'power-series', title: 'Power Series & Radius of Convergence', blurb: 'Series in powers of $(x - c)$, and where they converge.', strategicAnchor: 'Ratio test on $|a_{n+1}/a_n|<1$ gives the radius $R$. Endpoints $c\\pm R$ need separate hand-checks — ratio test is inconclusive there.', exampleProblem: 'Find the interval of convergence of $\\displaystyle\\sum_{n=1}^{\\infty} \\dfrac{(x - 2)^n}{n \\cdot 3^n}$.' },
      { id: 'taylor-maclaurin', title: 'Taylor & Maclaurin Series', blurb: 'Approximate a function as a polynomial near a point.', strategicAnchor: '$\\sum f^{(n)}(0)\\,x^n/n!$ (Maclaurin). Memorize the big four — $e^x$, $\\sin x$, $\\cos x$, $1/(1-x)$ — and derive others by substitution, differentiation, or integration.', exampleProblem: 'Find the Maclaurin series for $f(x) = x \\sin(x^2)$ up to $x^7$.' },
      { id: 'parametric-arc-length', title: 'Parametric Equations & Arc Length', blurb: 'Curves $(x(t), y(t))$ and the length of an arc.', strategicAnchor: '$\\dfrac{dy}{dx}=\\dfrac{dy/dt}{dx/dt}$. Arc length $L=\\int\\sqrt{(dx/dt)^2+(dy/dt)^2}\\,dt$ — the integrand is speed.', exampleProblem: 'Find the arc length of $x = t^2$, $y = \\dfrac{2}{3} t^3$ from $t = 0$ to $t = 1$.' },
      { id: 'polar-area', title: 'Polar Coordinates & Polar Area', blurb: 'Curves $r = f(\\theta)$ and the area they enclose.', strategicAnchor: '$A=\\dfrac{1}{2}\\int_\\alpha^\\beta r^2\\,d\\theta$. Find where $r=0$ to set the right $\\theta$-bounds.', exampleProblem: 'Find the area inside one petal of the rose $r = 2 \\sin(3\\theta)$.' },
    ],
  },
  {
    id: 'calc-3',
    title: 'Calculus III',
    blurb: 'Multivariable derivatives, gradients, multiple integrals, vector fields.',
    topics: [
      { id: 'vectors-3d', title: 'Vectors in 2D and 3D', blurb: 'Components, magnitude, unit vectors, and basic operations.', strategicAnchor: 'Componentwise add and scale. $|\\vec v|=\\sqrt{a^2+b^2+c^2}$. Unit vector: $\\hat v=\\vec v/|\\vec v|$.', exampleProblem: 'Given $\\vec{u} = \\langle 1, -2, 3 \\rangle$ and $\\vec{v} = \\langle 4, 0, -1 \\rangle$, find a unit vector in the direction of $2\\vec{u} - 3\\vec{v}$.' },
      { id: 'dot-cross-product', title: 'Dot & Cross Products', blurb: '$\\vec{u} \\cdot \\vec{v}$ is a scalar; $\\vec{u} \\times \\vec{v}$ is a vector.', strategicAnchor: 'Dot: $\\vec u\\cdot\\vec v=|\\vec u|\\,|\\vec v|\\cos\\theta$, zero iff perpendicular. Cross: vector perpendicular to both, magnitude $|\\vec u|\\,|\\vec v|\\sin\\theta$ (parallelogram area), zero iff parallel.', exampleProblem: 'Find the area of the triangle with vertices $A = (1, 0, 0)$, $B = (0, 2, 0)$, $C = (0, 0, 3)$.' },
      { id: 'lines-planes-surfaces', title: 'Lines, Planes & Surfaces', blurb: 'Vector and parametric forms for lines; normal-vector form for planes.', strategicAnchor: 'Line: $\\vec r(t)=P_0+t\\vec v$. Plane: $\\vec n\\cdot(\\vec r-P_0)=0$. For a plane through three points, cross two edge vectors to get $\\vec n$.', exampleProblem: 'Find the equation of the plane through $(1, 2, 3)$, $(2, 0, -1)$, and $(0, 1, 4)$.' },
      { id: 'partial-derivatives', title: 'Partial Derivatives', blurb: 'Differentiate w.r.t. one variable, treating the others as constants.', strategicAnchor: 'Differentiate w.r.t. one variable; freeze the others as constants. Notation: $\\partial f/\\partial x$ or $f_x$.', exampleProblem: 'Find $\\dfrac{\\partial f}{\\partial x}$ and $\\dfrac{\\partial f}{\\partial y}$ for $f(x, y) = x^3 y^2 + e^{xy}$.' },
      { id: 'gradient-directional', title: 'Gradient & Directional Derivatives', blurb: '$\\nabla f$ points in the direction of steepest ascent.', strategicAnchor: '$\\nabla f$ points up the steepest slope; its magnitude is the max rate. Directional derivative in unit $\\vec u$: $\\nabla f\\cdot\\vec u$.', exampleProblem: 'Find the directional derivative of $f(x, y) = x^2 y + y^3$ at $(1, 2)$ in the direction of $\\langle 3, 4 \\rangle$.' },
      { id: 'tangent-planes', title: 'Tangent Planes & Linearization', blurb: 'Linear approximation to $f(x, y)$ at a point.', strategicAnchor: '$z=f(a,b)+f_x(a,b)(x-a)+f_y(a,b)(y-b)$ — the 2D analog of the tangent line. Use it as a linear approximation near $(a,b)$.', exampleProblem: 'Use linearization to approximate $\\sqrt{(2.05)^2 + (2.97)^2}$.' },
      { id: 'critical-points-2d', title: 'Critical Points & Second-Derivative Test', blurb: 'Max, min, and saddle points of $f(x, y)$.', strategicAnchor: '$\\nabla f=\\vec 0$ for critical points. Classify with $D=f_{xx}f_{yy}-f_{xy}^2$: $D>0$ and $f_{xx}>0$ → min; $D>0$ and $f_{xx}<0$ → max; $D<0$ → saddle.', exampleProblem: 'Find and classify all critical points of $f(x, y) = x^3 - 3xy + y^3$.' },
      { id: 'double-integrals', title: 'Double Integrals', blurb: 'Integrate over a 2D region by iterated single integrals.', strategicAnchor: 'Sketch the region first. Pick the order ($dy\\,dx$ vs $dx\\,dy$) that gives easier inner bounds.', exampleProblem: 'Compute $\\displaystyle\\iint_R xy \\, dA$ where $R$ is bounded by $y = x$ and $y = x^2$.' },
      { id: 'coordinate-changes', title: 'Polar / Cylindrical / Spherical', blurb: 'Pick coordinates that match the geometry to simplify integration.', strategicAnchor: 'See $x^2+y^2$ or a disk → polar, $dA=r\\,dr\\,d\\theta$. Cylinder → cylindrical. See $x^2+y^2+z^2$ or a sphere/cone → spherical, $dV=\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$.', exampleProblem: 'Compute $\\displaystyle\\iint_D \\sqrt{x^2 + y^2} \\, dA$ where $D$ is the disk of radius 2 centered at the origin.' },
      { id: 'line-integrals', title: 'Line Integrals', blurb: 'Integrate along a curve.', strategicAnchor: 'Parametrize the curve $\\vec r(t)$; express $f$ and $ds$ (or $\\vec F\\cdot d\\vec r$) in $t$. Conservative field? Use $\\int_C\\vec F\\cdot d\\vec r=f(\\text{end})-f(\\text{start})$.', exampleProblem: 'Compute $\\displaystyle\\int_C (x + y^2) \\, ds$ where $C$ is $\\vec{r}(t) = \\langle t, t^2 \\rangle$, $0 \\le t \\le 1$.' },
      { id: 'surface-integrals', title: 'Surface Integrals', blurb: 'Integrate over a surface — scalar or flux integrals.', strategicAnchor: 'Parametrize $\\vec r(u,v)$; area element $dS=|\\vec r_u\\times\\vec r_v|\\,du\\,dv$. Closed surface → divergence theorem is usually faster.', exampleProblem: 'Find the flux of $\\vec{F} = \\langle x, y, z \\rangle$ across the sphere $x^2 + y^2 + z^2 = 4$ with outward normal.' },
      { id: 'green-stokes-divergence', title: 'Green / Stokes / Divergence', blurb: 'Convert between line, surface, and volume integrals.', strategicAnchor: 'Closed curve in the plane → Green\'s. Closed curve in 3D → Stokes. Closed surface → Divergence. Each trades a boundary integral for one over the interior.', exampleProblem: "Use Green's theorem to compute $\\displaystyle\\oint_C (y^2 \\, dx + x^2 \\, dy)$ around the triangle with vertices $(0,0)$, $(1,0)$, $(0,1)$." },
    ],
  },
  {
    id: 'discrete',
    title: 'Discrete Math',
    blurb: 'Logic, proofs, sets, relations, recursion, graph basics.',
    topics: [
      { id: 'propositional-logic', title: 'Propositional Logic & Equivalences', blurb: 'Use logic laws (De Morgan, distribution) to simplify or prove statements.', strategicAnchor: '$P\\to Q \\equiv \\neg P \\vee Q \\equiv \\neg Q\\to\\neg P$. De Morgan flips $\\wedge\\leftrightarrow\\vee$ when negating. Equivalences scale where truth tables don\'t.', exampleProblem: 'Show that $(P \\to Q) \\to P \\equiv P$.' },
      { id: 'predicate-logic', title: 'Predicate Logic & Quantifiers', blurb: '$\\forall$ (for all) and $\\exists$ (there exists) over a domain.', strategicAnchor: 'Negate by flipping the quantifier and negating inside: $\\neg\\forall x\\,P(x)\\equiv\\exists x\\,\\neg P(x)$. Quantifier order matters: $\\forall x\\,\\exists y$ ≠ $\\exists y\\,\\forall x$.', exampleProblem: 'Negate and simplify: $\\forall x \\in \\mathbb{R}, \\exists y \\in \\mathbb{R}, x + y = 0$.' },
      { id: 'proof-techniques', title: 'Proof Techniques', blurb: 'Direct, contrapositive, contradiction.', strategicAnchor: 'Direct: clean path from $P$ to $Q$. Contrapositive: when $\\neg Q$ gives a more concrete fact. Contradiction: assume $P\\wedge\\neg Q$, derive nonsense.', exampleProblem: 'Prove: if $n^2$ is even, then $n$ is even. (Hint: contrapositive is easier than direct.)' },
      { id: 'induction', title: 'Mathematical Induction', blurb: 'Prove a claim about all natural numbers by base case + inductive step.', strategicAnchor: 'Base case $P(1)$. Inductive hypothesis: assume $P(k)$. Inductive step: derive $P(k+1)$ using the IH explicitly.', exampleProblem: 'Prove $1 + 2 + \\cdots + n = \\dfrac{n(n+1)}{2}$ for all $n \\ge 1$.' },
      { id: 'set-operations', title: 'Sets & Set Identities', blurb: 'Unions, intersections, complements, and proving set equalities.', strategicAnchor: 'To prove $A=B$, show $A\\subseteq B$ and $B\\subseteq A$ — pick an arbitrary element of one side, prove it lives on the other.', exampleProblem: 'Prove $A \\cap (B \\cup C) = (A \\cap B) \\cup (A \\cap C)$.' },
      { id: 'relations', title: 'Relations & Equivalence Classes', blurb: 'Reflexive, symmetric, transitive — partitions from equivalences.', strategicAnchor: 'Equivalence relation = reflexive + symmetric + transitive. Every equivalence relation partitions the set into disjoint classes $[a]=\\{x:xRa\\}$.', exampleProblem: 'Show that "$a \\equiv b \\pmod{5}$" is an equivalence relation on $\\mathbb{Z}$. List the equivalence classes.' },
      { id: 'function-properties', title: 'Injective / Surjective / Bijective', blurb: 'Prove function properties straight from the definitions.', strategicAnchor: 'Injective: assume $f(a)=f(b)$, conclude $a=b$. Surjective: take any $y$ in the codomain, exhibit an $x$ with $f(x)=y$. Bijective = both.', exampleProblem: 'Show that $f: \\mathbb{R} \\to \\mathbb{R}, \\, f(x) = 2x + 3$ is bijective.' },
      { id: 'modular-arithmetic', title: 'Modular Arithmetic & Divisibility', blurb: '$a \\equiv b \\pmod{n}$ and arithmetic in $\\mathbb{Z}/n\\mathbb{Z}$.', strategicAnchor: '$a\\equiv b\\pmod n$ iff $n\\mid a-b$. You can reduce mod $n$ at any step in $+,-,\\times$. Fermat: $p$ prime, $p\\nmid a$ → $a^{p-1}\\equiv 1\\pmod p$ kills huge exponents.', exampleProblem: "Compute $7^{100} \\pmod{13}$ using Fermat's little theorem." },
      { id: 'recurrence-relations', title: 'Recurrence Relations', blurb: 'Closed-form for sequences defined recursively.', strategicAnchor: 'Solve the characteristic equation $r^2=c_1r+c_2$. Distinct roots → $ar_1^n+br_2^n$; repeated $r$ → $(a+bn)r^n$; complex → trig form.', exampleProblem: 'Solve: $a_n = 5 a_{n-1} - 6 a_{n-2}$, $a_0 = 1$, $a_1 = 4$.' },
      { id: 'graph-basics', title: 'Graph Theory Basics', blurb: 'Vertices, edges, paths, cycles, degrees.', strategicAnchor: 'Sum of degrees $=2E$ (handshake lemma). Euler circuit exists iff every vertex has even degree. Hamilton is hard in general — no clean test.', exampleProblem: 'Does the graph with vertices $\\{1, 2, 3, 4, 5\\}$ where each vertex connects to the others mod-5 by $\\pm 1$ have an Eulerian circuit?' },
      { id: 'trees-spanning', title: 'Trees & Spanning Trees', blurb: 'Connected acyclic graphs and minimum spanning trees.', strategicAnchor: 'Tree = connected, acyclic, exactly $V-1$ edges. MST: Kruskal (sort edges, add cheapest with no cycle) or Prim (grow from one vertex, add cheapest crossing edge).', exampleProblem: 'Show that a tree on $n$ vertices has exactly $n - 1$ edges (use induction on $n$).' },
      { id: 'counting-principles', title: 'Counting Principles', blurb: 'Addition and multiplication rules — the foundation of counting.', strategicAnchor: 'Stages multiply, disjoint cases add. Overlapping cases need inclusion–exclusion. When stuck, enumerate small cases first.', exampleProblem: 'How many 5-letter strings can be formed from the alphabet $\\{a, b, c, d, e\\}$ where no letter repeats and the string starts with a vowel ($a$ or $e$)?' },
    ],
  },
  {
    id: 'combinatorics',
    title: 'Combinatorics',
    blurb: 'Counting, permutations, generating functions, inclusion–exclusion.',
    topics: [
      { id: 'basic-counting', title: 'Addition & Multiplication Principles', blurb: 'The two foundational rules of counting.', strategicAnchor: 'Stages multiply, cases add. If you find yourself dividing, you\'re undoing a symmetry overcount.', exampleProblem: 'How many 4-digit PIN codes have at least one even digit?' },
      { id: 'permutations-combinations', title: 'Permutations & Combinations', blurb: 'Order matters → $P(n, k)$; order does not → $C(n, k)$.', strategicAnchor: 'Does order matter? Yes → $P(n,k)=\\dfrac{n!}{(n-k)!}$. No → $\\binom{n}{k}=\\dfrac{n!}{k!(n-k)!}$. Watch repetition separately.', exampleProblem: 'From 8 candidates, how many ways are there to (a) arrange 3 in a line, and (b) choose 3 for a committee?' },
      { id: 'permutations-constraints', title: 'Permutations with Constraints', blurb: 'Circular arrangements, repetition, and "adjacent" rules.', strategicAnchor: 'Circular: $(n-1)!$ (fix one seat to kill rotation). "Must be adjacent": glue them into one super-item, then permute internally. Duplicates: divide by $n_1!n_2!\\cdots$.', exampleProblem: 'In how many ways can 6 people sit around a round table if two specific people refuse to sit next to each other?' },
      { id: 'stars-and-bars', title: 'Stars and Bars', blurb: 'Count solutions to $x_1 + \\cdots + x_k = n$ with non-negative integers.', strategicAnchor: 'Lay out $n$ stars in a row; you need $k-1$ bars to chop them into $k$ bins. Pick which $k-1$ of the $n+k-1$ total slots are bars: $\\binom{n+k-1}{k-1}$. E.g. $x_1+x_2+x_3+x_4=10$ gives $\\binom{13}{3}=286$. For strictly positive, gift each variable a 1 first, then count with $n-k$ stars.', exampleProblem: 'How many non-negative integer solutions does $x_1 + x_2 + x_3 + x_4 = 10$ have?' },
      { id: 'binomial-theorem', title: 'Binomial Theorem', blurb: '$(x + y)^n = \\sum \\binom{n}{k} x^k y^{n-k}$.', strategicAnchor: 'To pull a coefficient out of $(ax+by)^n$: spot $k$ (the power of $x$), then write $\\binom{n}{k}\\,a^k b^{n-k}$. E.g. coefficient of $x^4$ in $(2x-3)^7$: $\\binom{7}{4}\\cdot 2^4\\cdot(-3)^3 = 35\\cdot 16\\cdot(-27) = -15120$.', exampleProblem: 'Find the coefficient of $x^4$ in $(2x - 3)^7$.' },
      { id: 'multinomial', title: 'Multinomial Coefficients', blurb: 'Generalize binomial to more than two groups.', strategicAnchor: 'Read the exponents off the term you want. The coefficient is $\\dfrac{n!}{e_1!\\,e_2!\\cdots e_k!}$ times each base raised to its exponent. E.g. coefficient of $x^2 y^3 z$ in $(2x+y+3z)^6$: $\\dfrac{6!}{2!\\,3!\\,1!}\\cdot 2^2\\cdot 1^3\\cdot 3 = 60\\cdot 12 = 720$.', exampleProblem: 'Find the coefficient of $x^2 y^3 z$ in $(2x + y + 3z)^6$.' },
      { id: 'inclusion-exclusion', title: 'Inclusion–Exclusion', blurb: '$|A \\cup B \\cup C| = $ singles $-$ doubles $+$ triples $-$ …', strategicAnchor: 'Why the alternating signs? Add the singles — you double-counted every pair, so subtract pairs. But triples got added 3 times and subtracted 3 times (net zero), so add them back. Each level corrects the previous over/undercount. Often easier: count the complement ("none of $A,B,C$") and subtract from the total.', exampleProblem: 'Of 100 people, 60 like coffee, 50 like tea, 30 like both. How many like neither?' },
      { id: 'pigeonhole', title: 'Pigeonhole Principle', blurb: 'If $n+1$ objects go in $n$ boxes, some box has $\\ge 2$.', strategicAnchor: '$n$ objects in $k$ boxes → some box has at least $\\lceil n/k\\rceil$. Existence without construction — find the pigeons, the boxes, and the conclusion follows.', exampleProblem: 'Show that among any 5 points in a $2 \\times 2$ square, two are at distance $\\le \\sqrt{2}$.' },
      { id: 'bijective-proofs', title: 'Combinatorial & Bijective Proofs', blurb: 'Prove $|A| = |B|$ by exhibiting a bijection.', strategicAnchor: 'To prove $|A|=|B|$: exhibit a bijection. Both sides count the same set in different ways — shorter and clearer than chasing factorials.', exampleProblem: 'Give a combinatorial proof: $\\sum_{k=0}^{n} \\binom{n}{k}^2 = \\binom{2n}{n}$.' },
      { id: 'generating-functions', title: 'Generating Functions', blurb: 'Encode a sequence as the coefficients of a power series.', strategicAnchor: '$\\dfrac{1}{1-x}=1+x+x^2+\\cdots$. Multiplying GFs convolves the sequences they encode. Use for recurrences, partitions, and identities.', exampleProblem: 'Find the coefficient of $x^{10}$ in $(1 + x + x^2 + \\cdots)^4$.' },
      { id: 'linear-recurrences-combinatorial', title: 'Linear Recurrences (Combinatorial)', blurb: 'Counting interpretations of $a_n = c_1 a_{n-1} + c_2 a_{n-2}$.', strategicAnchor: 'Condition on the last step to discover the recurrence, then solve via the characteristic equation. Tilings, paths, strings-avoiding-patterns all fit this mold.', exampleProblem: "How many binary strings of length $n$ have no two consecutive 1s? Set up the recurrence, solve, and identify the closed form (it's a famous sequence)." },
      { id: 'catalan-lattice', title: 'Catalan Numbers & Lattice Paths', blurb: 'The $n$-th Catalan number counts a half-dozen famous things.', strategicAnchor: 'Reflection trick: paths $(0,0)\\to(n,n)$ that never cross above $y=x$ = (all paths) − (bad paths). Every bad path bijects with a path to the reflected endpoint $(n-1,n+1)$, so bad count is $\\binom{2n}{n-1}$. Subtract: $C_n=\\binom{2n}{n}-\\binom{2n}{n-1}=\\dfrac{1}{n+1}\\binom{2n}{n}$. Same number counts balanced parens, binary trees, and $(n+2)$-gon triangulations.', exampleProblem: 'How many lattice paths go from $(0,0)$ to $(5,5)$ using only unit steps right or up, never crossing above the line $y = x$?' },
    ],
  },
  {
    id: 'linear-algebra',
    title: 'Linear Algebra',
    blurb: 'Vectors, matrices, eigenvalues, span, rank, decompositions.',
    topics: [
      { id: 'vectors-operations', title: 'Vectors & Vector Operations', blurb: 'Addition, scalar multiplication, dot product.', strategicAnchor: 'Componentwise add and scale. $\\vec u\\cdot\\vec v=\\sum u_iv_i=|\\vec u|\\,|\\vec v|\\cos\\theta$. Length: $|\\vec v|=\\sqrt{\\vec v\\cdot\\vec v}$.', exampleProblem: 'Given $\\vec{u} = (1, 2, -1, 3)$ and $\\vec{v} = (-2, 0, 4, 1)$, find $2\\vec{u} - \\vec{v}$, $\\vec{u} \\cdot \\vec{v}$, and $|\\vec{u}|$.' },
      { id: 'matrices-systems', title: 'Matrices & Systems of Equations', blurb: 'Write a linear system as $A\\vec{x} = \\vec{b}$.', strategicAnchor: 'A system becomes $A\\vec x=\\vec b$. Matrix product: $(AB)_{ij}=\\sum_k A_{ik}B_{kj}$. Not commutative — $AB\\ne BA$ in general.', exampleProblem: 'Write the system $\\begin{cases} 2x - y + z = 4 \\\\ x + 3y - 2z = -1 \\\\ -x + y + z = 2 \\end{cases}$ as $A\\vec{x} = \\vec{b}$ and identify $A$, $\\vec{x}$, $\\vec{b}$.' },
      { id: 'row-reduction', title: 'Row Reduction (RREF)', blurb: 'Reduce a matrix to RREF via elementary row operations — one op at a time.', strategicAnchor: 'Three operations: swap, scale by nonzero, add a multiple of one row to another. Pick a pivot, zero out below, move on — one operation per line.', exampleProblem: 'Reduce to RREF: $$\\begin{bmatrix} 1 & 2 & 1 \\\\ 2 & 3 & 3 \\\\ 1 & 1 & 2 \\end{bmatrix}$$' },
      { id: 'matrix-inverse', title: 'Matrix Inverses & Invertibility', blurb: '$A^{-1}$ exists iff $\\det A \\ne 0$; many equivalent conditions.', strategicAnchor: '$A^{-1}$ exists iff $\\det A\\ne 0$ (equivalently: RREF is $I$, columns independent, $A\\vec x=\\vec 0$ has only trivial solution). Compute by row-reducing $[A\\mid I]\\to[I\\mid A^{-1}]$. 2×2 shortcut: swap diagonal, negate off-diagonal, divide by $ad-bc$.', exampleProblem: 'Find the inverse of $A = \\begin{bmatrix} 1 & 2 & 3 \\\\ 0 & 1 & 4 \\\\ 5 & 6 & 0 \\end{bmatrix}$, or show it has none.' },
      { id: 'determinants', title: 'Determinants', blurb: 'A scalar that captures invertibility, area/volume scaling, orientation.', strategicAnchor: '2×2: $ad-bc$. Larger: cofactor expand along the row or column with the most zeros. Or row-reduce and track each operation\'s effect.', exampleProblem: 'Compute: $$\\det \\begin{bmatrix} 2 & 0 & 1 \\\\ 1 & 3 & 2 \\\\ 0 & 1 & 1 \\end{bmatrix}$$' },
      { id: 'span-basis-dimension', title: 'Span, Basis, Dimension', blurb: 'Span: all linear combinations. Basis: minimal spanning set. Dimension: size of any basis.', strategicAnchor: 'Stack vectors as columns, row-reduce: pivot in every column → linearly independent. Basis = independent spanning set; dimension = its size (same for any basis).', exampleProblem: 'Are $\\langle 1, 2, 3 \\rangle$, $\\langle 2, 4, 6 \\rangle$, $\\langle 1, 0, 1 \\rangle$ linearly independent?' },
      { id: 'four-subspaces', title: 'The Four Fundamental Subspaces', blurb: 'Column space, null space, row space, left null space — and how they fit.', strategicAnchor: 'For $m\\times n$ matrix $A$: $C(A),N(A^T)\\subseteq\\mathbb{R}^m$ orthogonally complement; $C(A^T),N(A)\\subseteq\\mathbb{R}^n$ likewise. Rank-nullity: $\\dim C(A)+\\dim N(A)=n$.', exampleProblem: 'For $A = \\begin{bmatrix} 1 & 2 & 0 & 1 \\\\ 2 & 4 & 1 & 3 \\\\ 0 & 0 & 1 & 1 \\end{bmatrix}$, find a basis for the column space, null space, and row space.' },
      { id: 'linear-transformations', title: 'Linear Transformations', blurb: 'Functions $T: V \\to W$ that respect addition and scaling.', strategicAnchor: 'Matrix of $T$: apply $T$ to each basis vector, stack results as columns. Kernel = null space of that matrix; image = its column space.', exampleProblem: 'Let $T: \\mathbb{R}^2 \\to \\mathbb{R}^2$ rotate vectors by $90°$ counterclockwise. Find its matrix in the standard basis, then compute $T(\\langle 3, 4 \\rangle)$.' },
      { id: 'eigenvalues', title: 'Eigenvalues & Eigenvectors', blurb: 'Find scalars $\\lambda$ and vectors $\\vec{v}$ with $A\\vec{v} = \\lambda\\vec{v}$.', strategicAnchor: 'Solve $\\det(A-\\lambda I)=0$ for $\\lambda$, then null space of $A-\\lambda I$ for each eigenvector. Triangular? Eigenvalues are the diagonal — done. 2×2 shortcut: $\\lambda_1+\\lambda_2=\\operatorname{tr}(A)$ and $\\lambda_1\\lambda_2=\\det(A)$ — solve those two equations in your head.', exampleProblem: 'Find the eigenvalues and eigenvectors of $A = \\begin{bmatrix} 4 & -2 \\\\ 1 & 1 \\end{bmatrix}$.' },
      { id: 'diagonalization', title: 'Diagonalization & Similarity', blurb: 'Decompose $A = PDP^{-1}$ where $D$ is diagonal.', strategicAnchor: '$n$ independent eigenvectors → $A=PDP^{-1}$ with $P$\'s columns the eigenvectors and $D$ diagonal of eigenvalues. Then $A^k=PD^kP^{-1}$ is trivial.', exampleProblem: 'Diagonalize $A = \\begin{bmatrix} 2 & 1 \\\\ 0 & 3 \\end{bmatrix}$ and use it to compute $A^{10}$.' },
      { id: 'inner-products-orthogonality', title: 'Inner Products & Orthogonality', blurb: 'Dot products, vector lengths, perpendicular vectors, Gram-Schmidt.', strategicAnchor: 'Orthogonal iff dot product is zero. Gram-Schmidt: subtract each vector\'s projections onto the already-built directions, then normalize.', exampleProblem: 'Use Gram-Schmidt on $\\langle 1, 1, 0 \\rangle$ and $\\langle 1, 0, 1 \\rangle$.' },
      { id: 'matrix-decompositions', title: 'Matrix Decompositions', blurb: 'Factor a matrix into pieces that reveal structure (LU, QR, SVD).', strategicAnchor: 'LU = row reduction without swaps; QR = Gram-Schmidt on columns; SVD = $U\\Sigma V^T$ for any matrix. Pick by purpose: solve systems, least squares, or deepest structure.', exampleProblem: 'Find the LU decomposition of $A = \\begin{bmatrix} 2 & 1 & 1 \\\\ 4 & 3 & 3 \\\\ 8 & 7 & 9 \\end{bmatrix}$.' },
    ],
  },
  {
    id: 'differential-equations',
    title: 'Differential Equations',
    blurb: 'Modeling change: separable, linear, second-order, Laplace, systems.',
    topics: [
      { id: 'intro-classification', title: 'Intro & Classification', blurb: 'ODE vs PDE; order, linearity, autonomous.', strategicAnchor: 'Order = highest derivative. Linear if $y$ and its derivatives appear to power 1, not multiplied together or inside other functions. Autonomous if $t$ is absent. Classification picks the method.', exampleProblem: "Classify each ODE by order and linearity: (a) $y'' + 3y' + 2y = \\sin t$; (b) $(y')^2 + y = t$; (c) $y'' + y \\sin(y) = 0$." },
      { id: 'separable', title: 'Separable Equations', blurb: 'When you can write $dy/dx = f(x) g(y)$.', strategicAnchor: '$\\dfrac{dy}{g(y)}=f(x)\\,dx$, integrate both sides, one constant $C$. Watch for equilibrium solutions where $g(y)=0$ — dividing can lose them.', exampleProblem: 'Solve: $\\dfrac{dy}{dx} = \\dfrac{x \\cos x}{y}$, $y(0) = 1$.' },
      { id: 'first-order-linear', title: 'First-Order Linear Equations', blurb: "Integrating factor for $y' + P(x) y = Q(x)$.", strategicAnchor: 'Standard form $y\'+P(x)y=Q(x)$. Integrating factor $\\mu=e^{\\int P\\,dx}$. Multiply through, LHS becomes $(\\mu y)\'$, integrate, solve for $y$.', exampleProblem: "Solve: $y' + 2xy = e^{-x^2}$." },
      { id: 'exact-equations', title: 'Exact Equations', blurb: 'When $M(x, y) \\, dx + N(x, y) \\, dy = 0$ is the differential of some $F$.', strategicAnchor: 'Check $\\partial M/\\partial y=\\partial N/\\partial x$. If exact, find $F$ with $F_x=M$, $F_y=N$; solution is $F(x,y)=C$.', exampleProblem: 'Solve: $(2xy + 3) \\, dx + (x^2 - 1) \\, dy = 0$.' },
      { id: 'substitutions', title: 'Bernoulli & Substitution Methods', blurb: 'Nonlinear forms that linearize after a clever substitution.', strategicAnchor: 'Bernoulli $y\'+Py=Qy^n$ → substitute $v=y^{1-n}$ to linearize. Homogeneous $dy/dx=F(y/x)$ → $v=y/x$ to separate. Transform into something you already know.', exampleProblem: "Solve: $y' + y = x y^2$ (Bernoulli with $n = 2$)." },
      { id: 'modeling-first-order', title: 'Modeling: Growth, Mixing, Cooling', blurb: 'First-order ODEs in the wild.', strategicAnchor: 'Growth: $dP/dt=kP$. Cooling: $dT/dt=-k(T-T_a)$. Mixing: $dy/dt=$ rate in $-$ rate out. Setting up the equation is most of the work.', exampleProblem: 'A 100-gallon tank starts with 5 lb of dissolved salt. Brine with 1 lb/gallon flows in at 3 gallons/min; well-mixed solution flows out at 3 gallons/min. Find the amount of salt after 30 minutes.' },
      { id: 'existence-uniqueness', title: 'Existence, Uniqueness & Phase Lines', blurb: 'When does a solution exist? When is it unique?', strategicAnchor: 'Picard: $f$ and $\\partial f/\\partial y$ continuous near $(t_0,y_0)$ → unique solution locally. Phase line for autonomous 1D: equilibria are zeros of $f$, stability from the sign of $f$ on either side.', exampleProblem: "For $y' = y(1 - y)$ (the logistic equation), find the equilibria and classify each as stable or unstable. Sketch the phase line." },
      { id: 'second-order-homogeneous', title: 'Linear 2nd-Order Homogeneous', blurb: "Constant coefficients: $ay'' + by' + cy = 0$.", strategicAnchor: 'Characteristic equation $ar^2+br+c=0$. Distinct real → $c_1e^{r_1t}+c_2e^{r_2t}$. Repeated $r$ → $(c_1+c_2t)e^{rt}$ (the $t$ factor is the structural fix). Complex $\\alpha\\pm\\beta i$ → $e^{\\alpha t}(c_1\\cos\\beta t+c_2\\sin\\beta t)$.', exampleProblem: "Solve $y'' - 4y' + 13y = 0$ with $y(0) = 1$, $y'(0) = 0$." },
      { id: 'undetermined-coefficients', title: 'Method of Undetermined Coefficients', blurb: "Guess the form of $y_p$ for nonhomogeneous $ay'' + by' + cy = g(t)$.", strategicAnchor: '$y=y_h+y_p$. Guess $y_p$ matching $g(t)$\'s shape (polynomial, $e^{\\alpha t}$, $\\sin/\\cos$). Resonance: if your guess already solves the homogeneous, multiply by $t$.', exampleProblem: "Solve $y'' + y = 3\\cos t$ (note: $\\cos t$ is a homogeneous solution — resonance!)." },
      { id: 'variation-of-parameters', title: 'Variation of Parameters & Cauchy-Euler', blurb: "When undetermined coefficients fails; Euler equations $t^2 y'' + \\cdots$.", strategicAnchor: '$y_p=u_1y_1+u_2y_2$ with $y_1,y_2$ homogeneous. Solve $u_1\'y_1+u_2\'y_2=0$ and $u_1\'y_1\'+u_2\'y_2\'=g/a$, then integrate. Cauchy-Euler: try $y=t^r$.', exampleProblem: "Solve the Cauchy-Euler equation: $t^2 y'' - 3t y' + 4y = 0$." },
      { id: 'laplace-transforms', title: 'Laplace Transforms', blurb: 'Algebra-ize ODEs by transforming to the $s$-domain.', strategicAnchor: '$\\mathcal{L}\\{y\'\\}=sY-y(0)$; $\\mathcal{L}\\{y\'\'\\}=s^2Y-sy(0)-y\'(0)$. Transform → algebra in $s$ → partial fractions → invert via table. Best for discontinuous or impulse forcing.', exampleProblem: "Use the Laplace transform to solve: $y'' + 4y = \\sin(2t)$, $y(0) = 0$, $y'(0) = 0$." },
      { id: 'systems-of-odes', title: 'Systems of Linear ODEs', blurb: "Couple equations $\\vec{x}' = A\\vec{x}$ — solve via eigenvalues.", strategicAnchor: '$\\vec x\'=A\\vec x$: each eigenpair $(\\lambda,\\vec v)$ contributes $\\vec v\\,e^{\\lambda t}$. Complex eigenvalues → spirals; classify the origin by eigenvalue signs (node, saddle, spiral, center).', exampleProblem: "Solve the system $\\vec{x}' = \\begin{bmatrix} 1 & 1 \\\\ 4 & 1 \\end{bmatrix} \\vec{x}$ with $\\vec{x}(0) = \\langle 1, 0 \\rangle$." },
    ],
  },
];

export const COURSES_BY_ID: Record<string, Course> = Object.fromEntries(
  COURSES.map((c) => [c.id, c]),
);

export function findTopic(courseId: string, topicId: string): { course: Course; topic: Topic } | null {
  const course = COURSES_BY_ID[courseId];
  if (!course) return null;
  const topic = course.topics.find((t) => t.id === topicId);
  if (!topic) return null;
  return { course, topic };
}
