/**
 * First-party funnel events.
 *
 * The client posts one small JSON body per step; this rolls them up per
 * (day, session) in KV, the same shape and the same trade-off as the cache
 * metrics. No vendor, no third-party script, no cookie, and nothing stored
 * that identifies a person beyond the Clerk id of someone who signed in.
 *
 * The endpoint is unauthenticated by necessity — the first two steps of the
 * funnel happen before anyone signs in — so everything it accepts is bounded:
 * a fixed event allowlist, a shape-checked session id, a whitelist of prop
 * keys with truncated values, and a per-IP daily cap on top. The allowlist is
 * what keeps a caller from minting arbitrary KV keys.
 */

/** The funnel, in order. Anything not on this list is refused. */
export const FUNNEL_EVENTS = [
  'route_view',
  'problem_submitted',
  'walkthrough_first_token',
  'walkthrough_completed',
  'walkthrough_error',
] as const;

export type FunnelEvent = (typeof FUNNEL_EVENTS)[number];

const EVENT_SET = new Set<string>(FUNNEL_EVENTS);

/** Session ids are generated by the client and become part of a KV key, so
 *  they are treated as untrusted input and must match this exactly. */
const SID_SHAPE = /^[A-Za-z0-9-]{8,64}$/;
/** Clerk user ids look like `user_2abc…`. */
const USER_ID_SHAPE = /^[A-Za-z0-9_-]{1,64}$/;

const STRING_PROPS = ['route', 'courseId', 'topicId', 'action', 'kind', 'detail'] as const;
const NUMBER_PROPS = ['ms', 'ttft_ms', 'chars', 'limit', 'used', 'status'] as const;
const MAX_PROP_CHARS = 80;

/** 30 days. Long enough to compare a launch week against the one after it. */
export const FUNNEL_TTL_SECONDS = 30 * 24 * 60 * 60;

/** A day's worth of sessions is read key by key, so the readout is bounded
 *  rather than unbounded on a day that goes unexpectedly well. */
const MAX_SESSIONS_PER_DAY = 1000;

export interface FunnelSession {
  day: string;
  firstSeen: number;
  lastSeen: number;
  /** Event name → how many times this session raised it. */
  steps: Record<string, number>;
  lastEvent: FunnelEvent;
  /** Present once the session signs in, so a drop-off maps to someone we can
   *  go ask. */
  userId?: string;
  lastRoute?: string;
  lastErrorKind?: string;
}

export interface ParsedEvent {
  event: FunnelEvent;
  sid: string;
  userId?: string;
  props: Record<string, string | number>;
}

function utcDay(d = new Date()): string {
  return d.toISOString().slice(0, 10);
}

/** Validates the posted body. Returns a reason rather than throwing so the
 *  handler can answer 400 with something a developer can act on. */
export function parseEventBody(
  raw: unknown,
): { ok: true; value: ParsedEvent } | { ok: false; reason: string } {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    return { ok: false, reason: 'body must be an object' };
  }
  const body = raw as Record<string, unknown>;

  if (typeof body.event !== 'string' || !EVENT_SET.has(body.event)) {
    return { ok: false, reason: 'unknown event' };
  }
  if (typeof body.sid !== 'string' || !SID_SHAPE.test(body.sid)) {
    return { ok: false, reason: 'bad session id' };
  }

  let userId: string | undefined;
  if (typeof body.userId === 'string' && USER_ID_SHAPE.test(body.userId)) {
    userId = body.userId;
  }

  const props: Record<string, string | number> = {};
  const rawProps =
    typeof body.props === 'object' && body.props !== null && !Array.isArray(body.props)
      ? (body.props as Record<string, unknown>)
      : {};
  for (const key of STRING_PROPS) {
    const v = rawProps[key];
    if (typeof v === 'string' && v) props[key] = v.slice(0, MAX_PROP_CHARS);
  }
  for (const key of NUMBER_PROPS) {
    const v = rawProps[key];
    if (typeof v === 'number' && Number.isFinite(v)) props[key] = v;
  }

  return { ok: true, value: { event: body.event as FunnelEvent, sid: body.sid, userId, props } };
}

/**
 * Merges one event into its session record.
 *
 * Read-modify-write on a single key, exactly like recordCacheMetrics: KV has
 * no atomic increment, so two events arriving in the same instant can lose
 * one of the two counts. This measures where people stop, not how many times
 * they clicked, and a step is counted once per session in the readout either
 * way — so the race cannot change an answer anyone reads.
 */
export async function recordEvent(kv: KVNamespace, e: ParsedEvent): Promise<void> {
  const day = utcDay();
  const key = `funnel:${day}:${e.sid}`;
  const now = Date.now();

  let existing: FunnelSession | null = null;
  try {
    existing = await kv.get<FunnelSession>(key, 'json');
  } catch {
    existing = null;
  }

  const session: FunnelSession = existing ?? {
    day,
    firstSeen: now,
    lastSeen: now,
    steps: {},
    lastEvent: e.event,
  };
  session.lastSeen = now;
  session.lastEvent = e.event;
  session.steps[e.event] = (session.steps[e.event] ?? 0) + 1;
  // Never cleared here: a session that signs in stays attributed for the rest
  // of the day. A sign-out mints a new session id on the client instead.
  if (e.userId) session.userId = e.userId;
  if (typeof e.props.route === 'string') session.lastRoute = e.props.route;
  if (e.event === 'walkthrough_error' && typeof e.props.kind === 'string') {
    session.lastErrorKind = e.props.kind;
  }

  await kv.put(key, JSON.stringify(session), { expirationTtl: FUNNEL_TTL_SECONDS });
}

export interface FunnelDay {
  day: string;
  sessions: number;
  /** Event name → how many distinct sessions reached it. */
  steps: Record<string, number>;
  /** True when the day held more sessions than one readout will walk. */
  truncated: boolean;
}

export interface FunnelReport {
  window_days: number;
  total: { sessions: number; steps: Record<string, number> };
  days: FunnelDay[];
}

function emptySteps(): Record<string, number> {
  const out: Record<string, number> = {};
  // Seeded in funnel order so the JSON reads top to bottom as the funnel.
  for (const e of FUNNEL_EVENTS) out[e] = 0;
  return out;
}

/**
 * Distinct sessions per step, per day — a real drop-off funnel rather than a
 * count of events. A session that spans UTC midnight is counted under both
 * days, which is the same convention every other daily rollup here uses.
 */
export async function readFunnel(kv: KVNamespace, days: number): Promise<FunnelReport> {
  const out: FunnelDay[] = [];
  const total = { sessions: 0, steps: emptySteps() };
  const now = new Date();

  for (let i = 0; i < days; i++) {
    const d = new Date(now);
    d.setUTCDate(d.getUTCDate() - i);
    const day = utcDay(d);
    const prefix = `funnel:${day}:`;

    const keys: string[] = [];
    let cursor: string | undefined;
    let truncated = false;
    while (keys.length < MAX_SESSIONS_PER_DAY) {
      const page = await kv.list({ prefix, cursor });
      for (const k of page.keys) keys.push(k.name);
      if (page.list_complete) break;
      cursor = page.cursor;
      if (!cursor) break;
    }
    if (keys.length > MAX_SESSIONS_PER_DAY) {
      truncated = true;
      keys.length = MAX_SESSIONS_PER_DAY;
    }

    const steps = emptySteps();
    let sessions = 0;
    for (const key of keys) {
      let s: FunnelSession | null = null;
      try {
        s = await kv.get<FunnelSession>(key, 'json');
      } catch {
        s = null;
      }
      if (!s) continue;
      sessions += 1;
      for (const name of Object.keys(s.steps)) {
        // One per session, however many times it fired.
        if (name in steps) steps[name] += 1;
      }
    }

    out.push({ day, sessions, steps, truncated });
    total.sessions += sessions;
    for (const name of Object.keys(steps)) total.steps[name] += steps[name];
  }

  return { window_days: days, total, days: out };
}
